'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'     Runtime Version:4.0.30319.1
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On

Imports System

Namespace My.Resources
    
    'This class was auto-generated by the StronglyTypedResourceBuilder
    'class via a tool like ResGen or Visual Studio.
    'To add or remove a member, edit your .ResX file then rerun ResGen
    'with the /str option, or rebuild your VS project.
    '''<summary>
    '''  A strongly-typed resource class, for looking up localized strings, etc.
    '''</summary>
    <Global.System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0"),  _
     Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
     Global.System.Runtime.CompilerServices.CompilerGeneratedAttribute(),  _
     Global.Microsoft.VisualBasic.HideModuleNameAttribute()>  _
    Friend Module Resources
        
        Private resourceMan As Global.System.Resources.ResourceManager
        
        Private resourceCulture As Global.System.Globalization.CultureInfo
        
        '''<summary>
        '''  Returns the cached ResourceManager instance used by this class.
        '''</summary>
        <Global.System.ComponentModel.EditorBrowsableAttribute(Global.System.ComponentModel.EditorBrowsableState.Advanced)>  _
        Friend ReadOnly Property ResourceManager() As Global.System.Resources.ResourceManager
            Get
                If Object.ReferenceEquals(resourceMan, Nothing) Then
                    Dim temp As Global.System.Resources.ResourceManager = New Global.System.Resources.ResourceManager("Neutrino_Calculator.Resources", GetType(Resources).Assembly)
                    resourceMan = temp
                End If
                Return resourceMan
            End Get
        End Property
        
        '''<summary>
        '''  Overrides the current thread's CurrentUICulture property for all
        '''  resource lookups using this strongly typed resource class.
        '''</summary>
        <Global.System.ComponentModel.EditorBrowsableAttribute(Global.System.ComponentModel.EditorBrowsableState.Advanced)>  _
        Friend Property Culture() As Global.System.Globalization.CultureInfo
            Get
                Return resourceCulture
            End Get
            Set
                resourceCulture = value
            End Set
        End Property
        
        Friend ReadOnly Property arccoshx() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("arccoshx", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property arccosy() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("arccosy", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property arccothx() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("arccothx", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property arccotx() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("arccotx", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property arccschx() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("arccschx", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property arccscy() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("arccscy", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property arcsechx() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("arcsechx", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property arcsecy() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("arcsecy", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property arcsinhx() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("arcsinhx", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property arcsiny() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("arcsiny", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property arctanhx() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("arctanhx", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property arctany() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("arctany", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property coshz() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("coshz", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property cosx() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("cosx", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property cothz() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("cothz", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property cotx() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("cotx", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property cschz() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("cschz", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property cscx() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("cscx", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property sechz() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("sechz", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property secx() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("secx", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property sinhz() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("sinhz", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property sinx() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("sinx", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property tanhz() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("tanhz", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property tanx() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("tanx", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
    End Module
End Namespace
